# Generated by Django 4.1.3 on 2023-01-05 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_client_comment_alter_employee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='service_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.service'),
        ),
        migrations.AddField(
            model_name='comment',
            name='worker_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee'),
        ),
    ]
