# Generated by Django 4.1.3 on 2023-01-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Zdjęcie'),
        ),
    ]
