# Generated by Django 4.1.3 on 2023-01-05 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_name_service_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='0000', max_length=20, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
