# Generated by Django 4.1.3 on 2023-01-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
