# Generated by Django 4.1.3 on 2023-01-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Start Date')),
                ('date_end', models.DateTimeField(verbose_name='End Date')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee')),
            ],
            options={
                'verbose_name': 'Unavailability',
                'verbose_name_plural': 'Unavailability',
            },
        ),
    ]
