# Generated by Django 4.1.3 on 2023-01-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_appointment_service_appointment_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unavailability',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='unavailability',
            old_name='date_start',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
    ]
