# Generated by Django 4.1.3 on 2023-01-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_appointment_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
