# Generated by Django 4.1.3 on 2023-01-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='unavailability',
            options={'verbose_name': 'Niedostępność', 'verbose_name_plural': 'Niedostępność'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Zrealizowana', 'Completed'), ('Zaplanowana', 'Scheduled'), ('Odwołana', 'Cancelled')], default='Zaplanowana', max_length=100),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='end_date',
            field=models.DateTimeField(verbose_name='Koniec'),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='start_date',
            field=models.DateTimeField(verbose_name='Początek'),
        ),
    ]
