# Generated by Django 4.1.3 on 2023-01-10 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_appointment_client_alter_appointment_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Zrealizowana', 'Zrealizowana'), ('Zaplanowana', 'Zaplanowana'), ('Odwołana', 'Odwołana')], default='Zaplanowana', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='service_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.service', verbose_name='Usługa'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=400, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(max_length=254, verbose_name='E-mail klienta'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=120, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='worker_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee', verbose_name='Fryzjer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='login',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Hasło'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='products',
            name='amount',
            field=models.IntegerField(verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='products',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='Producent'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(max_length=100, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='approx_time',
            field=models.DurationField(verbose_name='Przewidywany czas'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='Usługa'),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee', verbose_name='Fryzjer'),
        ),
    ]
